name: Release Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Version
        id: version
        run: |
          # Generate date-based version with commit SHA
          DATE=$(date -u +'%Y.%m.%d')
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "full=${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Multi-Platform Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            timveil/cockroachdb-dynamic-certs:latest
            timveil/cockroachdb-dynamic-certs:${{ steps.version.outputs.date }}
            timveil/cockroachdb-dynamic-certs:${{ steps.version.outputs.full }}
          # Add supply chain attestations for Docker Scout
          provenance: true
          sbom: true

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: timveil/cockroachdb-dynamic-certs
          short-description: "Spring Boot utility that dynamically generates CockroachDB certificates"